[plugins]
list = [
    "https://github.com/LegendEvent/pwnagotchi-custom-plugins/blob/main/achievements.py",
    "https://github.com/AlienMajik/pwnagotchi_plugins/blob/main/adsbsniffer.py",
    "https://github.com/bryzz42o/Pwnagotchi-fsociety-plugins/blob/main/AGE",
    "https://github.com/hannadiamond/pwnagotchi-plugins/blob/main/plugins/age.py",
    "https://github.com/Kaska89/pwnagotchi-EXPv2-plugin/blob/main/agev2.py",
    "https://github.com/evilsocket/pwnagotchi-plugins-contrib/blob/master/aircrackonly.py",
    "https://github.com/dadav/pwnagotchi-custom-plugins/blob/master/apfaker.py",
    "https://github.com/itsdarklikehell/pwnagotchi-plugins/blob/master/apprise-notify.py",
    "https://github.com/evilsocket/pwnagotchi-plugins-contrib/blob/master/auto_backup.py",
    "https://github.com/itsdarklikehell/pwnagotchi-plugins/blob/master/auto-hotspot.py",
    "https://github.com/evilsocket/pwnagotchi/blob/master/pwnagotchi/plugins/default/auto-update.py",
    "https://github.com/troystauffer/home_base/blob/master/away_base.py",
    "https://github.com/itsdarklikehell/pwnagotchi-plugins/blob/master/banthex-de.py",
    "https://github.com/V0r-T3x/pwnagotchi_plugins/blob/main/plugins/banthex.py",
    "https://github.com/shir0tetsuo/pwnagotchi-plugins/blob/main/basiclight.py",
    "https://github.com/arturandre/pwnagotchi-beacon-plugins/blob/main/beaconify.py",
    "https://github.com/kripthor/pwnagotchi-beacons/blob/master/plugin/beacons.py",
    "https://github.com/SilenTree12th/pwnagotchi_plugins/blob/main/better_apfaker.py",
]

[scripts]
list = [
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/backup.sh",
    "https://github.com/probablyoffline/pwnagotchi-setup/blob/main/cleanup-service.sh",
    "https://github.com/probablyoffline/pwnagotchi-setup/blob/main/default-routes.sh",
    "https://github.com/bronekalmar/fastcrwpa-script/blob/main/fastcrwpa.sh",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/language.sh",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/linux_connection_share.sh",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/macos_connection_share.sh",
    "https://github.com/xenDE/pwnagotchi-tools/blob/master/ohc.founds.insert.py",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/openbsd_connection_share.sh",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/preview.py",
    "https://github.com/sokdr/Pwnaclear/blob/main/pwnaclear.sh",
    "https://github.com/JD-2006/pwnagotchi-plugins-scripts_JD-2006/blob/main/Scripts/Pwnagotchi-JSON-to-Wigle-CSV.py",
    "https://github.com/dervishe-/pwnagotchictl/blob/master/pwnagotchictl",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/pypi_upload.sh",
    "https://github.com/probablyoffline/pwnagotchi-setup/blob/main/reset-brain.sh",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/restore.sh",
    "https://github.com/probablyoffline/pwnagotchi-setup/blob/main/waveshare3.sh",
    "https://github.com/evilsocket/pwnagotchi/blob/master/scripts/win_connection_share.ps1",
    "https://github.com/xenDE/pwnagotchi-tools/blob/master/wpa-sec.founds.insert.py",
    "https://github.com/wpa-2/tele.py/blob/main/tele.py"
]

[mods]
list = [
    "https://github.com/FamosoMocoso/pwnagotchi_custom_ui",
    "https://github.com/V0r-T3x/pwnagotchi_LCD_colorized_darkmode",
    "https://github.com/roodriiigooo/PWNAGOTCHI-CUSTOM-FACES-MOD",
    "https://github.com/solution-libre/pwnagotchi-hdmi-viewer",
    "https://github.com/NoxiousKarn/Showerthoughts"
]

[apps]
list = []
